packages:
  # Libraries
  - 'packages/lit'
  - 'packages/angular-wrapper'
  - 'packages/react-wrapper'
  # Apps
  - 'apps/storybook'
  - 'apps/angular-ng19-pl3.1-mainmenu'
  - 'apps/react-19-pl3.1-mainmenu'
