// THIS FILE IS AUTO-GENERATED BY THE WRAPPER-GENERATOR SCRIPT. DO NOT EDIT.

import {
  Component,
  ChangeDetectionStrategy,
  Input,
  Output,
  EventEmitter,
  ElementRef,
  ViewChild,
  AfterViewInit,
  OnDestroy,
  CUSTOM_ELEMENTS_SCHEMA,
  booleanAttribute,
} from "@angular/core";
import type { PlButton } from "@liebherr2/plnext";

@Component({
  selector: "pl-button-angular",
  standalone: true,
  template: `
    <pl-button
      #elementRef
      [attr.disabled]="disabled ? '' : null"
      [attr.label]="_label"
      [attr.type]="_type"
      [attr.variant]="_variant"
    >
      <ng-content></ng-content>
    </pl-button>
  `,
  styles: [":host { display: inline-block; }"],
  changeDetection: ChangeDetectionStrategy.OnPush,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class PlButtonAngular implements AfterViewInit, OnDestroy {
  @ViewChild("elementRef") elementRef!: ElementRef<PlButton>;
  private _listenerCtl = new AbortController();

  // --- Inputs ---

  /** Maps to the "disabled" boolean attribute of the web component (present if true, absent if false). */
  @Input({ transform: booleanAttribute }) disabled: boolean = false;

  protected _label: string = "";
  /** Maps to the "label" attribute of the web component (string). */
  @Input()
  set label(value: string | null | undefined) {
    this._label = (value ?? "") as string;
  }
  get label(): string {
    return this._label;
  }

  protected _type: string = "button";
  /** Maps to the "type" attribute of the web component (string). */
  @Input()
  set type(value: string | null | undefined) {
    this._type = (value ?? "button") as string;
  }
  get type(): string {
    return this._type;
  }

  protected _variant: string = "primary";
  /** Maps to the "variant" attribute of the web component (string). */
  @Input()
  set variant(value: string | null | undefined) {
    this._variant = (value ?? "primary") as string;
  }
  get variant(): string {
    return this._variant;
  }

  // --- Outputs ---

  /** Emits when the "pl-button-click" event is fired by the web component. */
  @Output() plButtonClick = new EventEmitter<CustomEvent<any>>();

  // --- Lifecycle hooks ---
  ngAfterViewInit() {
    const nativeElement = this.elementRef.nativeElement;

    nativeElement.addEventListener(
      "pl-button-click",
      (event: Event) => {
        this.plButtonClick.emit(event as CustomEvent);
      },
      { signal: this._listenerCtl.signal },
    );
  }

  ngOnDestroy() {
    this._listenerCtl.abort();
  }
}
