// THIS FILE IS AUTO-GENERATED BY THE WRAPPER-GENERATOR SCRIPT. DO NOT EDIT.

import {
  Component,
  ChangeDetectionStrategy,
  Input,
  Output,
  EventEmitter,
  ElementRef,
  ViewChild,
  AfterViewInit,
  CUSTOM_ELEMENTS_SCHEMA,
  booleanAttribute,
} from "@angular/core";
import type { PlIcon } from "@liebherr2/plnext";

@Component({
  selector: "pl-icon-angular",
  standalone: true,
  template: `
    <pl-icon
      #elementRef
      [decorative]="decorative"
      [iconName]="_iconName"
      [label]="_label"
    >
      <ng-content></ng-content>
    </pl-icon>
  `,
  styles: [":host { display: inline-block; }"],
  changeDetection: ChangeDetectionStrategy.OnPush,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class PlIconAngular implements AfterViewInit {
  @ViewChild("elementRef") elementRef!: ElementRef<PlIcon>;

  // --- Inputs ---
  
  /** Maps to the "decorative" attribute of the web component. */
  @Input({ transform: booleanAttribute }) decorative: boolean = false;

  protected _iconName: string = "";
  /** Maps to the "iconName" attribute of the web component. */
  @Input()
  set iconName(value: string | null | undefined) {
    this._iconName = value ?? "";
  }
  get iconName(): string {
    return this._iconName;
  }

  protected _label: string = "";
  /** Maps to the "label" attribute of the web component. */
  @Input()
  set label(value: string | null | undefined) {
    this._label = value ?? "";
  }
  get label(): string {
    return this._label;
  }

  // --- Outputs ---
  

  // --- Lifecycle hooks ---
  ngAfterViewInit() {
    const nativeElement = this.elementRef.nativeElement;
    
  }
}