// THIS FILE IS AUTO-GENERATED BY THE WRAPPER-GENERATOR SCRIPT. DO NOT EDIT.

import {
  Component,
  ChangeDetectionStrategy,
  Input,
  Output,
  EventEmitter,
  ElementRef,
  ViewChild,
  AfterViewInit,
  CUSTOM_ELEMENTS_SCHEMA,
  booleanAttribute,
} from "@angular/core";
import type { PlItemlist } from "@liebherr2/plnext";

@Component({
  selector: "pl-itemlist-angular",
  standalone: true,
  template: `
    <pl-itemlist
      #elementRef
      [headline-label]="_headlineLabel"
    >
      <ng-content></ng-content>
    </pl-itemlist>
  `,
  styles: [":host { display: inline-block; }"],
  changeDetection: ChangeDetectionStrategy.OnPush,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class PlItemlistAngular implements AfterViewInit {
  @ViewChild("elementRef") elementRef!: ElementRef<PlItemlist>;

  // --- Inputs ---
  
  protected _headlineLabel: string = "";
  /** Maps to the "headline-label" attribute of the web component. */
  @Input()
  set headlineLabel(value: string | null | undefined) {
    this._headlineLabel = value ?? "";
  }
  get headlineLabel(): string {
    return this._headlineLabel;
  }

  // --- Outputs ---
  

  // --- Lifecycle hooks ---
  ngAfterViewInit() {
    const nativeElement = this.elementRef.nativeElement;
    
  }
}