// THIS FILE IS AUTO-GENERATED BY THE WRAPPER-GENERATOR SCRIPT. DO NOT EDIT.

import {
  Component,
  ChangeDetectionStrategy,
  Input,
  Output,
  EventEmitter,
  CUSTOM_ELEMENTS_SCHEMA,
  booleanAttribute,
} from "@angular/core";

// Side-effect import: registers this web component once at runtime
import "@liebherr2/plnext/components/itemlist/pl-itemlist.js";

@Component({
  selector: "pl-itemlist-angular",
  standalone: true,
  template: `
    <pl-itemlist
      [attr.headline-label]="_headlineLabel"
      [data]="data"
    >
      <ng-content></ng-content>
    </pl-itemlist>
  `,
  styles: [":host { display: block; }"],
  changeDetection: ChangeDetectionStrategy.OnPush,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class PlItemlistAngular {
  // --- Inputs (simple attributes) ---
  
  protected _headlineLabel: string = "";
  /** Maps to the "headline-label" string attribute. */
  @Input()
  set headlineLabel(value: string | null | undefined) {
    this._headlineLabel = (value ?? "") as string;
  }
  get headlineLabel(): string {
    return this._headlineLabel;
  }

  // --- Inputs (complex properties) ---
  
  /** Complex property "data" (set as DOM property, not attribute). */
  @Input() data: { key: string; value: string }[] = [];

  // --- Outputs ---
  
}