export const applauncherMockData = [
  {
    id: 1,
    name: 'dashboard',
    displayName: 'Component Shop',
    iconName: 'webshop',
    url: 'https://my.liebherr.com/',
    openInNewTab: false,
    isFavorite: true,
  },
  {
    id: 2,
    name: 'dashboard',
    displayName: 'Crane Planner 2.0',
    iconName: 'crane-planner',
    url: 'https://my.liebherr.com/',
    openInNewTab: false,
    isFavorite: true,
  },
  {
    id: 3,
    name: 'dashboard',
    displayName: 'Digital Crane Operator',
    iconName: 'e-learning',
    url: 'https://my.liebherr.com/',
    openInNewTab: false,
    isFavorite: true,
  },
  {
    id: 4,
    name: 'dashboard',
    displayName: 'Earthmoving Shop',
    iconName: 'webshop',
    url: 'https://my.liebherr.com/',
    openInNewTab: false,
  },
  {
    id: 5,
    name: 'dashboard',
    displayName: 'Dashboard',
    iconName: 'home-2',
    url: 'https://my.liebherr.com/',
    openInNewTab: false,
  },
  {
    id: 6,
    name: 'dashboard',
    displayName: 'Dashboard',
    iconName: 'home-2',
    url: 'https://my.liebherr.com/',
    openInNewTab: true,
  },
  {
    id: 7,
    name: 'dashboard',
    displayName: 'Dashboard',
    iconName: 'home-2',
    url: 'https://my.liebherr.com/',
    openInNewTab: false,
  },
  {
    id: 8,
    name: 'dashboard',
    displayName: 'Dashboard',
    iconName: 'home-2',
    url: 'https://my.liebherr.com/',
    openInNewTab: true,
  },
  {
    id: 9,
    name: 'dashboard',
    displayName: 'Dashboard',
    iconName: 'home-2',
    url: 'https://my.liebherr.com/',
    openInNewTab: true,
  },
];
