const demoImage =
  'https://www-assets.liebherr.com/media/bu-media/lhbu-corp/images/specials/wind-energy/liebherr-lwe-wind-energy-1920x1920_w384_h384.jpg';

export const basketMockData = [
  {
    id: '915443108',
    sku: 'Art. no.: TC-10023',
    name: 'Hydraulic Cylinder',
    imageUrl: demoImage,
    totalPrice: 800,
    currency: 'EUR',
    discountAmount: 200,
    quantity: 3,
    badgeTopText: 'Re',
    badgeBottomText: 'Action',
  },
  {
    id: '915431108',
    sku: 'Art. no.: TC-10023',
    name: 'Slewing Ring Bearing',
    imageUrl: null,
    totalPrice: 25000,
    currency: 'EUR',
    discountAmount: 5000,
    quantity: 1,
    badgeTopText: '',
    badgeBottomText: '',
  },
  {
    id: '915431208',
    sku: 'Art. no.: TC-10023',
    name: 'Load Hook',
    imageUrl: null,
    totalPrice: 900,
    currency: 'EUR',
    discountAmount: 150,
    quantity: 2,
    badgeTopText: 'Re',
    badgeBottomText: '',
  },
  {
    id: '915024808',
    sku: 'Art. no.: TC-10023',
    name: 'Mast Section Bold Set',
    imageUrl: demoImage,
    totalPrice: 800,
    currency: 'EUR',
    discountAmount: 0,
    quantity: 1,
    badgeTopText: '',
    badgeBottomText: 'Action',
  },
  {
    id: '914269008',
    sku: 'Art. no.: TC-10023',
    name: 'Operator Cabin Window',
    imageUrl: null,
    totalPrice: 800,
    currency: 'EUR',
    discountAmount: 100,
    quantity: 99,
    badgeTopText: '',
    badgeBottomText: '',
  },
];
